apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qPswXm5GxXbrxwiuTNqJhBFrDkDZtJ6hogt3XFNDvTAZZA6mZ4Wqa9p8GM2a8s/8LDPJ3TXTWuePzq4lk7kO94X+VOeOfo/BqZ7zV+Lfh/7mVGjOn7O0LKtE0m/FZosfPhu46XYwff9qhTagBtW3Fxy45WiNfp+rfkLmEFnABE/qwqLCj+ODi9Phgdt5QzdudkLqf/iwymk1isHBMZ88iejKUt9zWAv/Uj/EOZQkIX9nuhvZfkRG/wZr8n9ZCUmmLe+ru9QtZfDRvARFysIdmQdiCJGk69WpspcjNVybUuU5ChI30RdJvCvKTlUdS6M6buyjE1R3m6dp2204OOFwDX/IEpmgwBZe+tAq3SsvDc/HO+kCe2NCeUNFc5ps00ze,iv:hgSvGo0Y/KsgJeWyuBN+Ed6QKkNVX8S8PtgAuMfcKmE=,tag:VsX7/hkT54vBo3ipJXBR+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:7qeexlYKl4cyJhvu6JsTjQQL/E5yMmxl02YErN70t+neVwtkrY/do77jiKX7bupw9S4Imt5g69CEw+TcAYJDW1vQwya3BdC6xrornAo3uGEV/gxN3Bg9tELRyNNEUdVWsQPTWztClGwR/xpORD5ijNdzMwDMYZ8XX8rJyExP+LWc4vXdVol7oUomcvXT4mXOya8DqvHe4Yd/ShCOd3/r7BnvTYwDe1UYLj7LAQmW2v8NcWQMeUiBX3mnV3I037fAKW38+wUMWpnGbSgQnA==,iv:U16kuj5U3VL0Up1JFxZMMGTwZiuPQcZ6ZjF56gxHhMI=,tag:AgbQJDc+oF1y6hvrzHJvzQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:IweuctWm+lt0bKhGyLGzUKFQQtzatNl1sqvb9j+Gi5gRVyaKShdq1iS3ooMk9RF0LBC4qxEe2jD6X4rV0tPg21qZWlo8ABSk3aZxUCFLk0588/7Ij8T2sjC4o8HvWD/dAX3CAQLhe/QppqxwxBfhwG3SsIUG0gIsNdDimO21XPNg37mR3/bpRhNGh+7n5CHjk7v1jBSe8dewi/8dQjZRghixl4cWG47mIEcF,iv:gM2ELaZkUT6uDudWqVpnEMcdrhrRWFcM1TYheqGZYeQ=,tag:PrXk1auMeBiKdMQ4qaZEUw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g53rkvekhxufznvdwyvdfsvxdy5crvup2u7dvhtsqvzl8drwh90sq9gtzr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Uk9OY1MyMUxndmhNWm9w
            VTFFaC9sYy8wSXo4T2tBQmxsdk1ZUjJHalJZCis1YndjUk9weEk0b1AzT1NPN2tC
            V3dDbHhLWDBKUFpma2ZPVlBJWDkyNGcKLS0tIDlxTDdaWHdBZnprTE9GeWhxMjQ2
            NytFVW9yR2dHL3NLbXhKc1RrMnZuNzQKqaQ0UFE5PeAUcjZyj7+eD93YaxUCpCXU
            nFHFgvaqEYp1j3jKc9pnm4juE5LPYoVEkB1ro141/lbC91UM5T8HRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T07:19:51Z"
    mac: ENC[AES256_GCM,data:aAUhWSNKlKd3tPACepyTTiDNZBJePGtcYUaKrozzpYptIbgbQtC5XsVlqN5YlDC2qbH7bXr/5VuXwk7gISg2i+ZiRhV+c7FEoZtBxokYXtcEwfpTxPrPI0gB7uSqdvOZcQ/+xGki8/s4DKoC5MYTTS0U5Amfr7VCzrIj9g3fbLo=,iv:NrnIa8kXKoydqFRNrv3Wi7AKJl5BuXCRWarDSyW+IdY=,tag:0lUlj2PxAD3fUmS7hPMRGg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
